### ISSUE TITLE
Getting Error after running.

### ISSUE THREAD

**Issue by ashish1500616** [blackode/online-resume#1]
![image](https://user-images.githubusercontent.com/19726282/50347913-476e0200-055d-11e9-8c75-b74269364c1f.png)

**Comment by blackode** [comment]
The empty `_mixins` file causing the above error. 

[loading mixins bug fixed](https://github.com/blackode/online-resume/pull/2/commits/bda1523cdfff91ef693b08fb53f19762f4876586)
