### ISSUE TITLE
I Forked the Project To Build A Site For Myself (And Need Help)

### ISSUE THREAD

**Issue by SamGreenwood1** [blackode/online-resume#4]
When I try to open it blank white page loads but none of the elements do. I checked the dev tools and it looks like for some reason only index.html and a couple of CSS files get loaded in. How do I fix this? 

My Repo: https://github.com/SamGreenwood1/online-resume/

**Comment by SamGreenwood1** [comment]
I changed the repo because I realized that since I had forked it GitHub would annoy me about being out of sync with your version so I created a new repo. The repo itself is private but I sent you an invite to collaborate so you can access it.

**Comment by SamGreenwood1** [comment]
Now when I load the page this message appears at the top: 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/20076209/168496048-b1e2be09-229e-4f6e-a862-7bdf3363c554.png">

**Comment by blackode** [comment]
This has been fixed already.... I don't know how you are getting this. There isn't mixins file to import. So, It is giving you that error.
Either remove that importing line or add mixins file.

**Comment by blackode** [comment]
Check this https://github.com/blackode/online-resume/pull/2

**Comment by SamGreenwood1** [comment]
There's weird header text. How do I fix it?

**Comment by blackode** [comment]
@SamGreenwood1 what's that weird header text? can you screenshot that?

**Comment by SamGreenwood1** [comment]
What I posted and you said that you fixed.

**Comment by SamGreenwood1** [comment]
I figured out how to remove it from the page. I think that text wasn't commented out properly. The theme still isn't working.
